services:
  - type: web
    name: project-storage-tracker-api
    runtime: node
    plan: free
    buildCommand: "bash build.sh"
    startCommand: "cd backend && npm start"
    envVars:
      - key: NODE_VERSION
        value: "20.x"
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
